image: maven:3.5.4-jdk-8-alpine
    
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

cache:
  paths:
    - .m2/
  key: ${CI_COMMIT_REF_SLUG} # Cache per branch 

stages:
  - build
  - test
#  - deploy

build:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS install"

integration-test:
  stage: test
  script:
    - "mvn $MAVEN_CLI_OPTS install -DskipTests" 
    - cd monticore-generator/it
    - "mvn --settings ../../settings.xml clean verify"

integration-test-emf:
  stage: test
  script:
    - "mvn $MAVEN_CLI_OPTS install -DskipTests" 
    - cd monticore-generator/it
    - "mvn --settings ../../settings.xml clean install -P emf-it-tests"

integration-test-experiments:
  stage: test
  script:
    - "mvn $MAVEN_CLI_OPTS install -DskipTests" 
    - cd monticore-generator/it/experiments
    - "mvn --settings ../../../settings.xml clean install"

#deploy:
#  stage: deploy
#  script:
#    - "mvn $MAVEN_CLI_OPTS deploy -DskipTests"