image: maven:3.6.0-jdk-8

cache:
  paths:
    - target/

stages:
  - build

variables:
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
