image: maven:3.6.0-jdk-8

cache:
  paths:
    - monticore-cli/target/
    - monticore-grammar/target/
    - monticore-generator/target/
    - monticore-maven/target/
    - monticore-runtime/target/
    - monticore-emf-runtime/target/
    - monticore-templateclassgenerator/target/

stages:
  - build

variables:
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
