image: maven:3.5.4-jdk-8-alpine
    
variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

stages:
  - build
#  - deploy

build:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS install -DskipTests"

#deploy:
#  stage: deploy
#  script:
#    - "mvn $MAVEN_CLI_OPTS deploy -DskipTests"