image: maven:3.5.4-jdk-8-alpine
    
variables:
  MAVEN_OPTS: -Dmaven.repo.local=/cache/maven.repository
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

stages:
  - build
#  - deploy

build:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS install"

integration-test:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS install -DskipTests" 
    - cd monticore-generator/it
    - "mvn $MAVEN_CLI_OPTS clean verify"

integration-test-emf:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS install -DskipTests" 
    - cd monticore-generator/it
    - "mvn $MAVEN_CLI_OPTS clean install -P emf-it-tests"

integration-test-experiments:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS install -DskipTests" 
    - cd monticore-generator/it/experiments
    - "mvn $MAVEN_CLI_OPTS clean instal"

#deploy:
#  stage: deploy
#  script:
#    - "mvn $MAVEN_CLI_OPTS deploy -DskipTests"