image: maven:3.5.4-jdk-8-alpine
    
variables:
  MAVEN_OPTS: ""
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository


stages:
  - build
  - deploy

build:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS install"

deploy:
  stage: deploy
  script:
    - "mvn $MAVEN_CLI_OPTS deploy -DskipTests"