image: maven:3.5.4-jdk-8-alpine
    
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - "mvn clean package $MAVEN_CLI_OPTS -DskipTests"
  artifacts:
    paths:
        # upload classes and resources
      - target/
      - monticore-runtime/target/classes/
      - monticore-emf-runtime/target/classes/
      - monticore-grammar/target/classes/
      - monticore-generator/target/classes/
      - monticore-cli/target/classes/
      - monticore-maven/monticore-maven-plugin/target/classes/
      - monticore-templateclassgenerator/target/classes/
      
      # upload test classes and resources
      - monticore-runtime/target/test-classes/
      - monticore-emf-runtime/target/test-classes/
      - monticore-grammar/target/test-classes/
      - monticore-generator/target/test-classes/
      - monticore-cli/target/test-classes/
      - monticore-maven/monticore-maven-plugin/target/test-classes/
      - monticore-templateclassgenerator/target/test-classes/

unittest:
  stage: test
  dependencies:
    - build
  script:
    - "mvn surefire:test $MAVEN_CLI_OPTS"

# integrationtest:
#   stage: test
#   dependencies:
#     - build-job
#   script:
#     - "mvn verify $MAVEN_CLI_OPTS"
#   artifacts:
#     paths:
#       - target/

# deploy:
#   stage: deploy
#   artifacts:
#     paths:
#       - "target/*.jar"