image: maven:3.6.0-jdk-8

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-s settings.xml --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

build:
  stage: build
  script:
    - mvn $MAVEN_OPTS compile

test:
  stage: test
  script:
    mvn $MAVEN_OPTS test
