image: maven:3.5.4-jdk-8-alpine

variables:
  MC_MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"
  MC_MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

cache:
  paths:
    - .m2/
  key: ${CI_COMMIT_REF_SLUG} # Cache per branch


before_script:
    - chmod +x monticore-gradle/gradlew

stages:
  - build
  - trigger
  - test

build_dev:
  stage: build
  script:
    - "mvn $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS deploy -Dpass=$password -Duser=$username -DdeployAtEnd=true"
    - cd monticore-gradle
    - "./gradlew build"
    - "./gradlew publish -PmavenPassword=$password -PmavenUser=$username"
  only:
    - dev
    - newSymtab
    - refactoring_with_new_symtab

build_latest-grammar:
  stage: build
  script:
    - "mvn $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS deploy"
  only:
    - latest-grammar

build_branches:
  stage: build
  script:
    - "mvn $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS install"
  except:
    - dev
    - master
    - ci/gitlab-runner
    - latest-grammar

integration-test:
  stage: test
  script:
    - cd monticore-generator/it
    - "mvn --settings ../../settings.xml $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS clean verify"
    
staging:
  stage: test
  trigger:
    project: monticore/languages/automaton
    branch: newSymtab_gen
#
#integration-test-emf:
#  stage: test
#  script:
#    - cd monticore-generator/it
#    - "mvn --settings ../../settings.xml $MAVEN_OPTS clean install -P emf-it-tests"
#
#integration-test-experiments:
#  stage: test
#  script:
#    - cd monticore-generator/it/experiments
#    - "mvn --settings ../../../settings.xml $MAVEN_OPTS clean install"
