image: maven:3.5.4-jdk-8-alpine

stages:
  - compile
  - test
  
cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"# -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

job 1:
  stage: compile
  script:
    - mvn $MAVEN_CLI_OPTS install -DskipTests=true
    
job 2: 
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test