image: maven:3.5.4-jdk-8-alpine
    
variables:
  MAVEN_OPTS: ""
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - "mvn $MAVEN_CLI_OPTS compile"

test:
  stage: test
  dependencies:
    - build
  script:
    - "mvn $MAVEN_CLI_OPTS test"

# deploy:
#   stage: deploy
#   artifacts:
#     paths:
#       - "target/*.jar"