image: maven:3.5.4-jdk-8-alpine

stages:
  - build
  - test
  
cache:
  paths:
    - .m2/

variables:
  MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode -Dmaven.repo.local=.m2"# -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN"

build:
  stage: build
  script:
    - mvn $MAV$MAVEN_CLI_OPTS install -DskipTests=true
    
test: 
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS surefire:test