# (c) https://github.com/MontiCore/monticore
image: registry.git.rwth-aachen.de/monticore/container-registry/gradle:6.8.2-jdk8

#include:
#  - template: Code-Quality.gitlab-ci.yml
#
variables:
  MC_MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"
  GRADLE_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"
  MC_MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
  SONAR_OPTS: "-Dsonar.login=$sonarUser -Dsonar.password=$sonarPassword"


before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

#cache:
#  paths:
#    - .m2/
#    - .gradle/wrapper
#  key: ${CI_COMMIT_REF_SLUG} # Cache per branch

stages:
  - build
  - test
  - deploy
  - sonar
  - trigger_languages
  - report
  - check
  - mirror

build:
  stage: build
  script:
    - "cd monticore-generator && gradle build $GRADLE_OPTS -Pci"
    - "cd .. && gradle buildMC $GRADLE_OPTS -Pci"
  artifacts:
    paths:
      - ".gradle"
      - "*/target"
      - "*/.gradle"
    expire_in: 1 week
  only:
    - merge_requests
    - branches
  except:
    - master
      
build_mvn_plugin:
  stage: build
  image: registry.git.rwth-aachen.de/monticore/container-registry/maven:3-jdk-8
  script:
    - "cd monticore-maven-plugin && mvn $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS install"
  only:
    - merge_requests
    - branches
  except:
    - master

test_01experiments:
  stage: test
  dependencies:
    - build
  script:
    - "gradle -p monticore-test/01.experiments build $GRADLE_OPTS -Pci"
  only:
    - merge_requests
    - branches
  except:
    - master

test_02experiments:
  stage: test
  dependencies:
    - build
  script:
    - "gradle -p monticore-test/02.experiments build $GRADLE_OPTS -Pci"
  only:
    - merge_requests
    - branches
  except:
    - master

test_it:
  stage: test
  dependencies:
    - build
  script:
    - "gradle -p monticore-test/it build $GRADLE_OPTS -Pci"
  only:
    - merge_requests
    - branches
  except:
    - master

test_it_emf:
  stage: test
  dependencies:
    - build
  script:
    - "gradle -p monticore-test/it build -PbuildProfile=emf $GRADLE_OPTS -Pci"
  only:
    - merge_requests
    - branches
  except:
    - master

test_grammar_it:
  stage: test
  dependencies:
    - build
  script:
    - "gradle -p monticore-test/monticore-grammar-it build $GRADLE_OPTS -Pci"
  only:
    - merge_requests
    - branches
  except:
    - master

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - "gradle deployMC -PmavenPassword=$password -PmavenUser=$username $GRADLE_OPTS -Pci"
  only:
    - dev
  except:
    - master
      
deploy_mvn_plugin:
  stage: deploy
  image: registry.git.rwth-aachen.de/monticore/container-registry/maven:3-jdk-8
  dependencies:
    - build
  script:
    - "cd monticore-maven-plugin && mvn $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS deploy -Dpass=$password -Duser=$username"
  only:
    - dev
  except:
    - master

sonar:
  stage: sonar
  needs: ["build"]
  dependencies:
    - build
  script:
    - "gradle sonarMC $GRADLE_OPTS $SONAR_OPTS -Pci"
  allow_failure: true
  only:
    - dev
  except:
    - master

trigger-automata:
  stage: trigger_languages
  allow_failure: true
  trigger:
    project: monticore/languages/automaton
    branch: master
  only:
    - dev

trigger-cd4a-dev:
  stage: trigger_languages
  trigger:
    project: monticore/cd4analysis/cd4analysis
    branch: develop
  only:
    - dev

trigger-sd-dev:
  stage: trigger_languages
  trigger:
    project: monticore/statechart/sd-language
    branch: dev
  only:
    - dev

trigger-fd-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/feature-diagram
    branch: develop
  only:
    - dev

trigger-guidsl-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/gui-dsl
    branch: master
  only:
    - dev

trigger-json-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/json
    branch: develop
  only:
    - dev

trigger-ma-dev:
  stage: trigger_languages
  trigger:
    project: monticore/montiarc/core
    branch: develop
  only:
    - dev

trigger-ocl-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/OCL
    branch: develop
  only:
    - dev

trigger-siunits-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/siunits
    branch: dev
  only:
    - dev

trigger-sc-dev:
  stage: trigger_languages
  trigger:
    project: monticore/statechart/sc-language
    branch: dev
  only:
    - dev

trigger-xml-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/xml
    branch: develop
  only:
    - dev

trigger-od-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/od
    branch: dev
  only:
    - dev

trigger-cd4a-master:
  stage: trigger_languages
  trigger:
    project: monticore/cd4analysis/cd4analysis
    branch: master
  only:
    - master

trigger-sd-master:
  stage: trigger_languages
  trigger:
    project: monticore/statechart/sd-language
    branch: master
  only:
    - master

trigger-fd-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/feature-diagram
    branch: master
  only:
    - master

trigger-guidsl-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/gui-dsl
    branch: master
  only:
    - master

trigger-json-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/json
    branch: master
  only:
    - master

trigger-ma-master:
  stage: trigger_languages
  trigger:
    project: monticore/montiarc/core
    branch: master
  only:
    - master

trigger-ocl-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/OCL
    branch: master
  only:
    - master

trigger-siunits-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/siunits
    branch: master
  only:
    - master

trigger-sc-master:
  stage: trigger_languages
  trigger:
    project: monticore/statechart/sc-language
    branch: master
  only:
    - master

trigger-xml-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/xml
    branch: master
  only:
    - master

trigger-od-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/od
    branch: master
  only:
    - master

pages:
  stage: report
  dependencies: []
  image: python:alpine
  before_script:
    - apk add gcc musl-dev python3-dev
    - pip install cython
    - pip install mkdocs
    - pip install mkdocs-material
  script:
    - sh docs/scripts/preprocessing.sh
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - schedules

checkMDLinks:
  stage: check
  needs: []
  allow_failure: true
  script:
    - "curl --location --header \"PRIVATE-TOKEN: $secibuildtoken\" \"https://git.rwth-aachen.de/api/v4/projects/monticore%2Fmdlinkchecker/jobs/artifacts/master/raw/target/libs/MDLinkCheckerCLI.jar?job=build\" --output MDLinkCheckerCLI.jar"
    - "url=https://git.rwth-aachen.de/monticore/monticore/-/tree/dev"
    - "linkCheckRes=$(java -jar MDLinkCheckerCLI.jar -url $url -t $secibuildtoken)"
    - "echo \"$linkCheckRes\""
    - "if [[ $linkCheckRes == *\"ERROR\"* ]]; then exit 1; fi"
  only:
    - dev

githubmirror:
  image: maven:3-jdk-8
  stage: mirror
  dependencies:
    - checkMDLinks
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SE_CIBUILD_SSH_PRIV_KEY")
    - echo "$SE_CIBUILD_SSH_PRIV_KEY" | tr -d '\r' | ssh-add -
    - git config --global user.email "noreply-ci@se-rwth.de"
    - git config --global user.name "MontiCore Mirroring Bot"
    - mkdir -p ~/.ssh
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script:
    - "curl --location --header \"PRIVATE-TOKEN: $secibuildtoken\" \"https://git.rwth-aachen.de/api/v4/projects/monticore%2Fmdlinkchecker/jobs/artifacts/master/raw/target/libs/MDLinkChangerCLI.jar?job=build\" --output MDLinkChangerCLI.jar"
    - sh pre/mirror.sh
    - cd ..
    - "if [ -d \"tmp\" ]; then rm -rf tmp; fi"
    - mkdir "tmp"
    - cd tmp
    - git clone git@github.com:MontiCore/monticore.git
    - cd ..
    - rm -r tmp/monticore/*
    - mv monticore/* tmp/monticore/
    - cd tmp/monticore
    - git add --all
    - "(git commit -m 'Updated branch with most recent version.') || true"
    - git push --force
    - cd ..
    - cd ..
    - rm -rf tmp
    - exit 0
  only:
    - dev


