site_name: MontiCore
theme:
  name: mkdocs

repo_url: https://git.rwth-aachen.de/monticore/monticore

nav:
  - Home: 'index.md'
  - Grammars: 'monticore-grammar/src/main/grammars/de/monticore/Grammars.md'