site_name: MontiCore
theme:
  name: 'material'
  extra_css:
    - 'stylesheets/extra.css'
  favicon: 'img/favicon.ico'
  logo:
    icon: 'computer'

repo_url: https://github.com/MontiCore/monticore/
edit_uri: ""

copyright: '(c) https://github.com/MontiCore/monticore'

nav:
  - Home: 'README.md'
  - 'Getting Started': 'GettingStarted.md'
  - Grammars:
      - 'General': 'monticore-grammar/src/main/grammars/de/monticore/Grammars.md'
      - 'Expressions': 'monticore-grammar/src/main/grammars/de/monticore/expressions/README.md'
      - 'Literals': 'monticore-grammar/src/main/grammars/de/monticore/literals/README.md'
      - 'Types': 'monticore-grammar/src/main/java/de/monticore/types/check/README.md'
      - Languages: 'MCLanguages.md'
  - Publications: 'Publications.md'
  - 'More Information':
      - Changelog: 'CHANGELOG.md'
      - License: '00.org/Licenses/LICENSE-MONTICORE-3-LEVEL.md'
      - Reports: 'Reports.md'
      - 'FAQ': 'FAQ.md'



